List<Map<String, dynamic>> dummyLamaranPekerjaan = [
  {
    'idLamaranPekerjaan': 1,
    'idPostPekerjaan': 1,
    'idPelamar': 1,
    'status': 'diproses',
    'createdAt': DateTime.now(),
  },
  {
    'idLamaranPekerjaan': 2,
    'idPostPekerjaan': 2,
    'idPelamar': 1,
    'status': 'diterima',
    'createdAt': DateTime.now(),
  },
  {
    'idLamaranPekerjaan': 3,
    'idPostPekerjaan': 3,
    'idPelamar': 1,
    'status': 'ditolak',
    'createdAt': DateTime.now(),
  },
  {
    'idLamaranPekerjaan': 4,
    'idPostPekerjaan': 4,
    'idPelamar': 1,
    'status': 'diproses',
    'createdAt': DateTime.now(),
  },
  {
    'idLamaranPekerjaan': 5,
    'idPostPekerjaan': 5,
    'idPelamar': 1,
    'status': 'diterima',
    'createdAt': DateTime.now(),
  },
  {
    'idLamaranPekerjaan': 6,
    'idPostPekerjaan': 6,
    'idPelamar': 1,
    'status': 'ditolak',
    'createdAt': DateTime.now(),
  },
  {
    'idLamaranPekerjaan': 7,
    'idPostPekerjaan': 7,
    'idPelamar': 1,
    'status': 'diproses',
    'createdAt': DateTime.now(),
  },
  {
    'idLamaranPekerjaan': 8,
    'idPostPekerjaan': 8,
    'idPelamar': 1,
    'status': 'diterima',
    'createdAt': DateTime.now(),
  },
  {
    'idLamaranPekerjaan': 9,
    'idPostPekerjaan': 9,
    'idPelamar': 1,
    'status': 'ditolak',
    'createdAt': DateTime.now(),
  },
  {
    'idLamaranPekerjaan': 10,
    'idPostPekerjaan': 10,
    'idPelamar': 1,
    'status': 'diproses',
    'createdAt': DateTime.now(),
  },
];
